const profaneWords = [
  "arse",
  "arsehead",
  "arsehole",
  "ass",
  "ass hole",
  "asshole",
  "bastard",
  "bitch",
  "bloody",
  "bollocks",
  "brotherfucker",
  "bugger",
  "bullshit",
  "child-fucker",
  "Christ on a bike",
  "Christ on a cracker",
  "cock",
  "cocksucker",
  "crap",
  "cunt",
  "dammit",
  "damn",
  "damned",
  "damn it",
  "dick",
  "dick-head",
  "dickhead",
  "dumb ass",
  "dumb-ass",
  "dumbass",
  "dyke",
  "faggot",
  "father-fucker",
  "fatherfucker",
  "fuck",
  "fucker",
  "fucking",
  "god dammit",
  "goddammit",
  "God damn",
  "god damn",
  "goddamn",
  "Goddamn",
  "goddamned",
  "goddamnit",
  "godsdamn",
  "hell",
  "holy shit",
  "horseshit",
  "in shit",
  "jackarse",
  "jack-ass",
  "jackass",
  "Jesus Christ",
  "Jesus fuck",
  "Jesus Harold Christ",
  "Jesus H. Christ",
  "Jesus, Mary and Joseph",
  "Jesus wept",
  "kike",
  "mother fucker",
  "mother-fucker",
  "motherfucker",
  "nigga",
  "nigra",
  "nigger",
  "pigfucker",
  "piss",
  "prick",
  "pussy",
  "shit",
  "shitass",
  "shit ass",
  "shite",
  "sibling fucker",
  "sisterfuck",
  "sisterfucker",
  "slut",
  "son of a bitch",
  "son of a whore",
  "spastic",
  "sweet Jesus",
  "twat",
  "wanker",
];

// Function to check for profanity
function containsProfanity(input) {
  const lowerInput = input.toLowerCase();

  // Check each word or phrase in the profanity list
  return profaneWords.some((word) => lowerInput.includes(word.toLowerCase()));
}

module.exports = { containsProfanity };
